Dz7
PaladinVCT/MyRepo pull request #12
Opened 2019-03-27 18:29 UTC by PaladinVCT

2019-03-28 13:22 UTC, RomanKashenok commented on app/src/main/java/android/itacademy/by/dz6/activities/DetailsActivity.java
> +        DetailsFragment.onDataInitialize {
Я думаю лучше вынести в отдельный интерфейс. Не думаю, что элемент более низкого уровня, должен зависеть от содержания элемента более низкого уровня.

2019-03-28 13:22 UTC, RomanKashenok commented on app/src/main/java/android/itacademy/by/dz6/activities/DetailsActivity.java
> +        assert detailsFragment != null;
конструкция assert положит приложение при detailsFragment == null. Лучше использовать if

2019-03-28 13:22 UTC, RomanKashenok commented on app/src/main/java/android/itacademy/by/dz6/activities/MainActivity.java
> +        DetailsFragment.onDeletePressed {
onDataInitialize, onSavePressed, onDeletePressed  лучше организовать в отдельном интерфейсе

2019-03-28 13:22 UTC, RomanKashenok commented on app/src/main/java/android/itacademy/by/dz6/activities/MainActivity.java
> +            intent.putExtra("ID", id);
Будет вполне достаточно одного поля (Id) и по нему вытащить из коллекции студента в DetailsActivity. Поля и их количество в классе Student может меняться со временем.

2019-03-28 13:22 UTC, RomanKashenok commented on app/src/main/java/android/itacademy/by/dz6/fragments/DetailsFragment.java
> +    public interface onSavePressed {
Соглашения о именовании (должно быть с заглавной буквы)

2019-03-28 13:22 UTC, RomanKashenok commented on app/src/main/java/android/itacademy/by/dz6/fragments/DetailsFragment.java
> +    public interface onDeletePressed {
Соглашения о именовании (должно быть с заглавной буквы)

2019-03-28 13:22 UTC, RomanKashenok commented on app/src/main/java/android/itacademy/by/dz6/fragments/DetailsFragment.java
> +    public interface onDataInitialize{
Соглашения о именовании (должно быть с заглавной буквы)

2019-03-28 13:22 UTC, RomanKashenok commented on app/src/main/java/android/itacademy/by/dz6/fragments/DetailsFragment.java
> +    onSavePressed onSaveActivityListener;
модификатор private было бы лучше (для всех трех объектов)

2019-03-28 13:22 UTC, RomanKashenok commented on app/src/main/java/android/itacademy/by/dz6/fragments/DetailsFragment.java
> +        onSaveActivityListener = (onSavePressed) context;
Все три объекта будут указывать на одну и ту же активити (одну из 2-х реализующих эти интерфейсы). Так что нет смысла инициализировать все три.

2019-03-28 13:22 UTC, RomanKashenok commented on app/src/main/java/android/itacademy/by/dz6/activities/MainActivity.java
> +
Возможно, в детали лучше передать только ID, а там заполнить поля? Сильно сложно получается - создать фрагмент, оттуда по ссылке на активити, в которой он был создан, дернуть метод инициализации в самой активити, который, в свою очередь дернет метод фрагмента, который был создан этой же активити.

2019-03-28 13:22 UTC, RomanKashenok commented on app/src/main/java/android/itacademy/by/dz6/activities/MainActivity.java
> +        assert detailsFragment != null;
упадет, если detailsFragment == null

2019-03-28 13:22 UTC, RomanKashenok commented on app/src/main/java/android/itacademy/by/dz6/fragments/RecycleFragment.java
> +//    private void filter(String text) {
комментирование при мерже лучше убирать

2019-03-28 13:22 UTC, RomanKashenok commented on app/src/main/java/android/itacademy/by/dz6/recycle/StudentAdapter.java
> +                        Catalogue.getInstance().getStudent(holder.getAdapterPosition()).getFirstName(),
лучше одной строкой взять самого студента, а дальше брать поля уже у него, не обращаясь трижды к коллекции

2019-04-02 20:22 UTC, tim-teacher requested changes

2019-04-02 20:22 UTC, jushlwest commented on app/src/main/java/android/itacademy/by/dz6/recycle/StudentViewHolder.java
> +    private ImageView photo;
лучше называете переменные с постфиксов по названию элемента photo ImageView, nameTextView и lastNameTextView.
fName и lName - вообще не понятно что то, сокращения это хорошо, но в меру :)

2019-04-02 20:22 UTC, jushlwest commented on app/src/main/java/android/itacademy/by/dz6/recycle/StudentAdapter.java
> +    onItemClickListener mainActivityListener;
private ну и причем тут в название слово Activity? Вы же можете реализовать этот интерфейс где угодна, во фрагменте например.

2019-04-02 20:22 UTC, jushlwest commented on app/src/main/java/android/itacademy/by/dz6/fragments/RecycleFragment.java
> +public class RecycleFragment extends Fragment {
Странное название, вообще фиг догадаешь что в нем)))

2019-04-02 20:22 UTC, jushlwest commented on app/src/main/java/android/itacademy/by/dz6/fragments/RecycleFragment.java
> +    boolean dualPane;
а зачем во фрагменте вам знать какой у вас режим?

2019-04-02 20:22 UTC, jushlwest commented on app/src/main/java/android/itacademy/by/dz6/activities/MainActivity.java
> +        recycleFragment.getAdapter().notifyDataSetChanged();
а почем в самом фрагменте нельзя сделать refresh? зачем перекидывать из активити? В фрагменте тоже есть onResume(), который можно использовать.

2019-04-04 07:37 UTC, PaladinVCT commented on app/src/main/java/android/itacademy/by/dz6/activities/MainActivity.java
> +        recycleFragment.getAdapter().notifyDataSetChanged();
В ландшафтном расположении при нажатии на кнопку удаления во фрагменте с деталями происходит удаление записи из синглтона и удаление фрагмента с деталями. Основной фрагмент со списком студентов recyclerView не уходит на паузу, поэтому refresh() вызывает MainActivity, которая реализует интерфейс обработки нажатия кнопок во фрагменте с деталями.

2019-04-06 10:02 UTC, jushlwest commented on app/src/main/java/android/itacademy/by/dz6/activities/MainActivity.java
> +        recycleFragment.getAdapter().notifyDataSetChanged();
ok

2019-04-06 10:04 UTC, tim-teacher approved these changes

2019-04-18 12:56 UTC, closed without merging