First app
PaladinVCT/MyRepo pull request #4
Opened 2019-02-25 07:53 UTC by PaladinVCT

Исключено дублирование findViewById

2019-02-25 19:09 UTC, tim-teacher requested changes

2019-02-25 19:09 UTC, jushlwest commented on app/src/main/java/android/itacademy/by/DZ1/FirstActivity.java
> +    final TextView textView1 = findViewById(R.id.textView1);
findViewById вызывается до метода onCreate, у вас разме nullPointer не падает? :)
до вызова метода setContentView() у вас ничего нет на экране и метод findViewById ничего не найдет

2019-02-25 20:45 UTC, PaladinVCT commented on app/src/main/java/android/itacademy/by/DZ1/FirstActivity.java
> +    final TextView textView1 = findViewById(R.id.textView1);
Добавлена переменная класса

2019-02-26 10:57 UTC, tim-teacher approved these changes
Апрув поставил но маленький нюанс только гляньте, оставил в комментах

2019-02-26 10:57 UTC, jushlwest commented on app/src/main/java/android/itacademy/by/DZ1/FirstActivity.java
> +        TextView textView1 = findViewById(R.id.textView1);
можно сразу присвоить переменное tv1 и tv2.

2019-02-26 11:00 UTC, PaladinVCT commented on app/src/main/java/android/itacademy/by/DZ1/FirstActivity.java
> +        TextView textView1 = findViewById(R.id.textView1);
Но ведь будет крашиться, если присвоить до исполнения метода onCreate()?

2019-02-26 12:19 UTC, closed without merging